### ISSUE TITLE
Getting nil from map

### ISSUE THREAD

**Issue by c4s4** [mattn/anko#105]
Following script :

```
fmt=import("fmt")

foo = {"foo": "bar", "spam": "eggs"}
if foo["toto"] == nil {
    fmt.Println("nil")
} else {
    fmt.Println("non nil")
}
fmt.Printf("foo['toto']: %v\n", foo["toto"])
```

Produces output:

```
$ anko test.ank 
non nil
foo['toto']: <nil>
```

Which seems broken!

**Comment by MichaelS11** [comment]
The issue, at least in part, is how reflect MapIndex code works. For an item expression, the code is here:

https://github.com/mattn/anko/blob/master/vm/vmExpr.go#L479-L481

I was looking for another way to do "MapIndex" for a Reflect value but did not find anything when I did a quick search. If someone knows of another way, please let me know. Hopefully there is a better way that I just have not found yet.

I will look at this in more detail, but be at least few days before I can get to it. If someone else want start working on this sooner, please feel free. :) Otherwise, I will get to it.

**Comment by MichaelS11** [comment]
Have a pull request in for a fix:
https://github.com/mattn/anko/pull/107

In the long term, probably should look into adding syntax like `value, ok = aMap["key"]` to check if a key is present instead of relying on nil. There could be times when nil is a valid value.

**Comment by c4s4** [comment]
I agree, but I think we should provide a function such as `haskey(aMap)`, which is more in the script spirit that the Go syntax.

**Comment by MichaelS11** [comment]
I personally like the Go syntax better and think it would work just as well for scripting.

**Comment by c4s4** [comment]
If you prefer Go syntax, you should write Go scripts and run them with `go run` :o) Go is also a scripting language...

**Comment by MichaelS11** [comment]
I am not aware of a way to do in program Go with dynamic code (string) that can also pass variables in and out. If I am missing something, I would love to know.

May also want to note that most people using Anko are going to be coming from Go, so keeping the syntax the same when possible would probably be beneficial and helpful for people.

@mattn any thoughts if there should be a key check added?

**Comment by mattn** [comment]
#145 is candidate for this issue. I don't think #145 is better or not. For a candidate.
